alias ltunnel "ssh -D 4000 198.211.115.156 -l root"
alias .. "cd .."
alias ... "cd ../.."
alias ll "ls -la"
alias less "less -rFKRX"
alias startpg "pg_ctl -D /usr/local/var/postgres -l /usr/local/var/postgres/server.log start"
alias stoppg "pg_ctl -D /usr/local/var/postgres stop -s -m fast"
